# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

puts "Rails.env: #{Rails.env.inspect}"
puts "Database configurations: #{Rails.application.config.database_configuration.inspect}"

Rails.application.load_tasks
